# Generated by Django 5.2.10 on 2026-01-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BARREL', 'Barrel'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle')], max_length=20, unique=True)),
                ('liters_per_unit', models.DecimalField(decimal_places=3, help_text='How many liters per unit (e.g., 50 liters per barrel)', max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_locations', models.ManyToManyField(help_text='Locations where this beverage is available', related_name='beverages', to='inventory.location')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unittype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Number of units (barrels, trays, or bottles)', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.beverage')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
            options={
                'ordering': ['location', 'beverage'],
                'unique_together': {('beverage', 'location')},
            },
        ),
    ]
