# Generated by Django 5.2.10 on 2026-01-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unit type name (e.g., Tray, Barrel, Bottle)', max_length=100)),
                ('quantity', models.IntegerField(default=1, help_text='Number of items per unit (e.g., 6 bottles per tray, 12 bottles per tray)')),
            ],
            options={
                'ordering': ['name', 'quantity'],
                'unique_together': {('name', 'quantity')},
            },
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('liters_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='How many liters per unit for this specific beverage', max_digits=10)),
                ('alarm_minimum', models.IntegerField(default=1, help_text='Minimum quantity threshold for low stock alert')),
                ('color', models.CharField(default='rgb(54, 162, 235)', help_text="Color for chart display (e.g., 'rgb(255, 99, 132)' or '#ff6384')", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('available_locations', models.ManyToManyField(help_text='Locations where this beverage is available', related_name='beverages', to='inventory.location')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unittype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
