# Generated by Django 5.2.10 on 2026-01-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='inventory.location')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of units at time of count', max_digits=10)),
                ('liters', models.DecimalField(decimal_places=2, help_text='Total liters at time of count', max_digits=10)),
                ('unit_type_name', models.CharField(max_length=50)),
                ('liters_per_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.beverage')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
            ],
            options={
                'ordering': ['beverage__name'],
            },
        ),
    ]
