# Generated by Django 5.2.10 on 2026-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockcount_stockcountitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcount',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stockcountitem',
            name='stock_count',
        ),
        migrations.RemoveField(
            model_name='stockcountitem',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='unittype',
            name='liters_per_unit',
        ),
        migrations.AddField(
            model_name='beverage',
            name='liters_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, help_text='How many liters per unit for this specific beverage', max_digits=10),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockCount',
        ),
        migrations.DeleteModel(
            name='StockCountItem',
        ),
    ]
