# Generated by Django 5.2.10 on 2026-01-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stockcount_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unittype',
            options={'ordering': ['name', 'quantity']},
        ),
        migrations.AddField(
            model_name='unittype',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of items per unit (e.g., 6 bottles per tray, 12 bottles per tray)'),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(help_text='Unit type name (e.g., Tray, Barrel, Bottle)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='unittype',
            unique_together={('name', 'quantity')},
        ),
    ]
