# Generated by Django 5.2.10 on 2026-01-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_unittype_options_unittype_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='alarm_minimum',
            field=models.IntegerField(default=1, help_text='Minimum quantity threshold for low stock alert'),
        ),
    ]
