# Generated by Django 5.2.10 on 2026-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_beverage_alarm_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='color',
            field=models.CharField(default='rgb(54, 162, 235)', help_text="Color for chart display (e.g., 'rgb(255, 99, 132)' or '#ff6384')", max_length=20),
        ),
    ]
